" This file is out of date


"去除vi一致性
set nocompatible
filetype off
set backspace=indent,eol,start

syntax enable
set background=light
colorscheme solarized 



"语法高亮
syntax on

"行号
set number

"光标
set guicursor=a:block-Cursor-blinkon0

"刷新时间
set updatetime=100

"设置编码格式
set encoding=utf-8

"设置以unix的格式保存文件
set fileformat=unix

"设置字体
set guifont=monaco:h18

"突出显示当先行列
set cursorline
set cursorcolumn

"设置缩进格式
set cindent
set tabstop=4
set shiftwidth=4
set smartindent

"匹配括号
set showmatch
set matchtime=2

"隐藏滚动条
set guioptions-=r
set guioptions-=L
set guioptions-=b

"代码不折行
set nowrap




"指定插件管理器Vundle的安装路径
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"安装Vundle
Plugin 'gmarik/Vundle.vim'
"安装airline
Plugin 'vim-airline/vim-airline'
"安装nerdtree
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
"python插件
Plugin 'vim-scripts/indentpython.vim'
Plugin 'tell-k/vim-autopep8'
"自动补全
Plugin 'Valloric/YouCompleteMe'
"git工具
Plugin 'airblade/vim-gitgutter'
"markdowm
Plugin 'tpope/vim-markdown'
"自动补全括号
Plugin 'jiangmiao/auto-pairs'
"tag
"Plugin 'liuchengxu/vista.vim'
"Plugin 'prabirshrestha/async.vim'
"Plugin 'prabirshrestha/vim-lsp'
Plugin 'majutsushi/tagbar'

"theme
Plugin 'altercation/vim-colors-solarized'

call vundle#end()
"所有的插件都要在该行之前

filetype plugin indent on


"配置nerdtree
"F3快捷键调出和隐藏
map <F3> :NERDTreeToggle<CR>
let NERDTreeChDirMode=1
let NERDTreeIgnore=['\~$','\.pyc$','\.swp$']
let NERDTreeWinSize=25
"vim没有文件打开时自动打开nerdtree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
"vim打开文件夹时自动打开nerdtree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
"关闭vim时如果除了nerdtree没有别的文件那么自动关闭
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

"NERDTree显示git的信息
let g:NERDTreeShowGitStatus = 1
let g:NERDTreeUpdateOnWrite = 1
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ "Unknown"   : "?"
    \ }
"调出Tagbar
map <F2> :TagbarToggle<CR>

"tagbar尺寸
let g:tagbar_width=25

"设置记录50个历史命令
set history=50

"显示光标位置
set showcmd

"命令为两行
set laststatus=2

"启用鼠标
set mouse=a

"search
set incsearch
set ignorecase
set smartcase

