#! /bin/sh

# Autostart sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

xrdb -merge $HOME/.Xresources

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 0

# Autolaunch polybar
$HOME/.config/polybar/launch.sh

bspc config focus_follows_pointer true
bspc config top_padding 0

# Borders
bspc config border_width         2
bspc config focused_border_color "#353b45"
bspc config normal_border_color "#282c34"
bspc config borderless_monocle   true

# Gaps
bspc config gapless_monocle      true
bspc config window_gap          12

# Wallpaper
feh --bg-fill /usr/share/wallpapers/Breath2/contents/images/3840x2160.png &

bspc config split_ratio          0.50

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
